function createfigure(X1, YMatrix1, X2, YMatrix2, XData1, YData1)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2, XData1, YData1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 30-Mar-2020 20:46:57

% Create figure
figure1 = figure('Color',[1 1 1],'OuterPosition',[0 0 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Confirmed (fitted)','Color',[1 0 0]);
set(plot1(2),'DisplayName','Recovered (fitted)','Color',[0 0 1]);
set(plot1(3),'DisplayName','Deceased (fitted)','Color',[0 0 0]);

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Marker','o','LineWidth',2,'LineStyle','none',...
    'Parent',axes1);
set(plot2(1),'DisplayName','Confirmed (reported)','Color',[1 0 0]);
set(plot2(2),'DisplayName','Recovered (reported)','Color',[0 0 1]);
set(plot2(3),'DisplayName','Deceased  (reported)','Color',[0 0 0]);

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',2,'LineStyle','--',...
    'Color',[0.85 0.325 0.098]);

% Create ylabel
ylabel('Number of cases','FontSize',30);

% Create xlabel
xlabel('Time (days)','FontSize',30);

% Create title
title('Argentina COVID-19 Forecast','FontSize',45);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'XTickLabelRotation',45);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',20);

% Create textbox
annotation(figure1,'textbox',[0 0.9 0 0.2],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020 00:00:00',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0 0.9 0 0.2],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0 0.9 0 0.5],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0 1 0 1],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0 0.9 0 0.9],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.2 0.719607844948769 0.526948272932297 0.0803921550512314],...
    'String','Pico de infectados de 1.349460e+03 el día 14-Apr-2020',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',20,...
    'FontName','Arial');

